'use client'
import { Download } from "lucide-react";
import { Button } from "../ui/button";

export function DownloadSummaryButton({
  title,
  summaryText,
  fileName,
  createdAt
}: {
  title: string;
  summaryText: string;
  fileName: string;
  createdAt: string;
}) {
  const handleDownload = async () => {
    // Dynamic import to avoid SSR issues
    const html2pdf = (await import("html2pdf.js")).default;

    const summaryContent = `
      <div style="
        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; 
        background:#f9f9f9; 
        padding:30px; 
        border-radius:12px; 
        box-shadow:0 4px 12px rgba(0,0,0,0.1); 
        line-height:1.6; 
        color:#333;
        max-width:800px;
        margin:auto;
      ">
        
        <h2 style="text-align:center; color:#2c3e50; margin-bottom:10px;">
          ${title}
        </h2>
        
        <p style="text-align:center; font-size:14px; color:#888; margin-bottom:20px;margin-top:25px">
          Generated on: <strong>${new Date(createdAt).toLocaleDateString()}</strong>
        </p>
        
        <div style="font-size:16px; margin-bottom:30px; white-space:pre-line;">
          ${summaryText}
        </div>
        
        <div style="font-size:14px; padding:12px; background:#f3f6fa; border-left:4px solid #3498db; border-radius:6px; margin-bottom:20px;">
          📄 Original File: <strong>${fileName}</strong>
        </div>
        
        <div style="text-align:center; font-size:13px; color:#666; border-top:1px solid #eee; padding-top:10px;">
          Generated by <span style="color:#3498db; font-weight:bold;">Sommaire</span>
        </div>
      </div>
    `;

    // create element with summary content
    const element = document.createElement("div");
    element.innerHTML = summaryContent;

    // PDF options
    const opt = {
      margin: 0.5,
      filename: `Summary-${title.replace(/[^a-z0-9]/gi, '_')}.pdf`,
      image: { type: "jpeg", quality: 0.98 },
      html2canvas: { scale: 2 },
      jsPDF: { unit: "in", format: "a4", orientation: "portrait" }
    };

    // generate & download PDF
    html2pdf().set(opt).from(element).save();
  };

  return (
    <Button onClick={handleDownload} size="sm" className="h-8 px-3">
      Download Summary <Download className="ml-1 h-4 w-4" />
    </Button>
  );
}
